// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARg7T6MUK6nl2XP05dZkI3cuLBzcHrIu4',
    appId: '1:460587572384:web:9fa3b9b862defdbf983dc5',
    messagingSenderId: '460587572384',
    projectId: 'doodlenote-eaf2d',
    authDomain: 'doodlenote-eaf2d.firebaseapp.com',
    storageBucket: 'doodlenote-eaf2d.firebasestorage.app',
    measurementId: 'G-GTBDWVH4RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtWAePhI72tfCRXSVcRCTYEiklcIpDGdk',
    appId: '1:460587572384:android:7d3b21a87b62256c983dc5',
    messagingSenderId: '460587572384',
    projectId: 'doodlenote-eaf2d',
    storageBucket: 'doodlenote-eaf2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfnwFTR-Nvapwp-O_DVxSjhd4TFy6lX1w',
    appId: '1:460587572384:ios:54bb41691a423fc2983dc5',
    messagingSenderId: '460587572384',
    projectId: 'doodlenote-eaf2d',
    storageBucket: 'doodlenote-eaf2d.firebasestorage.app',
    iosBundleId: 'cl.obando.ivan.kiivu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfnwFTR-Nvapwp-O_DVxSjhd4TFy6lX1w',
    appId: '1:460587572384:ios:4adffaee348762b4983dc5',
    messagingSenderId: '460587572384',
    projectId: 'doodlenote-eaf2d',
    storageBucket: 'doodlenote-eaf2d.firebasestorage.app',
    iosBundleId: 'com.example.doodleNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARg7T6MUK6nl2XP05dZkI3cuLBzcHrIu4',
    appId: '1:460587572384:web:a674ca13b52330de983dc5',
    messagingSenderId: '460587572384',
    projectId: 'doodlenote-eaf2d',
    authDomain: 'doodlenote-eaf2d.firebaseapp.com',
    storageBucket: 'doodlenote-eaf2d.firebasestorage.app',
    measurementId: 'G-WJY254YR5J',
  );
}
